your_name  <- "Jinsung Sur"
your_github<- "jinsungsur"

dir.create("images", showWarnings = FALSE)

writeLines(c(
  "project:",
  "  type: website",
  "  output-dir: _site",
  "",
  "website:",
  paste0("  title: \"", your_name, " — biostat777 intro\""),
  "  navbar:",
  "    left:",
  "      - href: index.qmd",
  "        text: Home",
  "      - href: about.qmd",
  "        text: About",
  "      - href: example-analysis.qmd",
  "        text: Example analysis",
  "  page-footer:",
  "    left: \"© {{< meta author >}}\"",
  "    right: \"Built with Quarto\"",
  "",
  "format:",
  "  html:",
  "    theme: cosmo",
  "    toc: true",
  "    toc-depth: 3",
  "    code-tools: true",
  "    number-sections: false",
  "    smooth-scroll: true",
  "    css: styles.css",
  "",
  "metadata-files:",
  "  - _meta.yml"
), "_quarto.yml")

writeLines(paste0("author: \"", your_name, "\""), "_meta.yml")

writeLines(c(
  "h1, h2, h3 { letter-spacing: 0.2px; }",
  ".callout { border-radius: 12px; }",
  "img { border-radius: 10px; }"
), "styles.css")

# Home: no local image required (keeps render simple for novices).
writeLines(c(
  "---",
  "title: \"Welcome\"",
  "---",
  "",
  "# Hi, I’m ", your_name,"!",
  "",
  "I’m a BSPH MPH student interested in **biostatistics**, **epi methods**, and **data viz**.",
  "Here’s a tiny website for **biostat777** built with Quarto.",
  "",
  "::: {.column-margin}",
  "**Margin note**  ",
  "This is margin content.",
  ":::",
  "",
  "- Use the navbar above to see the **About** page and the **Example analysis**."
), "index.qmd")

writeLines(c(
  "---",
  "title: \"About\"",
  "---",
  "",
  "## A bit more about me",
  "",
  "- Focus: statistical programming workflows, reproducible research, and public-health analytics.",
  "- Tools: R, Quarto, git/GitHub, command line.",
  "",
  "### Contact",
  paste0("- GitHub: <https://github.com/", your_github, ">"),
  "- Email: you@example.edu"
), "about.qmd")

# Example analysis page meets all rubric items:
writeLines(c(
  "---",
  "title: \"Example analysis — Palmer Penguins\"",
  "bibliography: references.bib",
  "---",
  "",
  "::: {.callout-note}",
  "### Question & audience",
  "**Question.** How do body mass and bill dimensions vary by species and island?  ",
  "**Audience.** Peers learning basic EDA and tidyverse workflows.",
  ":::",
  "",
  "::: {.column-margin}",
  "**Data dictionary**  ",
  "<https://allisonhorst.github.io/palmerpenguins/reference/penguins.html>",
  ":::",
  "",
  "## Data and sources",
  "",
  "We use the **palmerpenguins** dataset [@horst2020palmerpenguins].  ",
  "Tidy tools: **dplyr** [@dplyr], **tidyr** [@tidyr], **ggplot2** [@ggplot2].  ",
  "Site is built with **Quarto** [@quarto].",
  "",
  "```{r}",
  "#| message: false",
  "library(tidyverse)",
  "library(palmerpenguins)",
  "library(janitor)",
  "",
  "peng <- penguins |> clean_names()",
  "peng |> dplyr::glimpse()",
  "```",
  "",
  "To include an **external image** (not created by me), save dataset art locally:",
  "",
  "```{r}",
  "#| echo: false",
  "if (!dir.exists(\"images\")) dir.create(\"images\")",
  "img <- \"images/penguins-art.png\"",
  "if (!file.exists(img)) {",
  "  download.file(",
  "    \"https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/man/figures/lter_penguins.png\",",
  "    destfile = img, mode = \"wb\"",
  "  )",
  "}",
  "```",
  "",
  "![](images/penguins-art.png){fig-alt=\"Palmer Station penguin art\" width=\"420\"}",
  "",
  "## Minimal wrangling (≥5 functions across dplyr/tidyr)",
  "",
  "```{r}",
  "peng2 <-",
  "  peng |>",
  "  tidyr::drop_na(species, island, body_mass_g, bill_length_mm, bill_depth_mm, flipper_length_mm) |>",
  "  dplyr::filter(body_mass_g > 2500) |>",
  "  dplyr::mutate(bmi = body_mass_g / (flipper_length_mm^2)) |>",
  "  dplyr::select(species, island, sex, body_mass_g, bill_length_mm, bill_depth_mm, bmi) |>",
  "  dplyr::arrange(species, island)",
  "```",
  "",
  "Reshape to long form for a faceted plot:",
  "",
  "```{r}",
  "peng_long <-",
  "  peng2 |>",
  "  tidyr::pivot_longer(",
  "    cols = c(bill_length_mm, bill_depth_mm),",
  "    names_to = \"bill_metric\", values_to = \"mm\"",
  "  )",
  "```",
  "",
  "## Three+ plots (3 different geoms; one uses faceting)",
  "",
  "### 1) Scatter + smooth",
  "```{r}",
  "ggplot(peng2, aes(bill_length_mm, bill_depth_mm, color = species)) +",
  "  geom_point(alpha = 0.7) +",
  "  geom_smooth(se = FALSE) +",
  "  labs(",
  "    title = \"Bill length vs depth by species\",",
  "    subtitle = \"Palmer Station LTER penguins\",",
  "    x = \"Bill length (mm)\", y = \"Bill depth (mm)\",",
  "    caption = \"Source: palmerpenguins\"",
  "  )",
  "```",
  "",
  "### 2) Boxplot",
  "```{r}",
  "ggplot(peng2, aes(species, body_mass_g, fill = species)) +",
  "  geom_boxplot() +",
  "  labs(",
  "    title = \"Body mass varies by species\",",
  "    x = \"Species\", y = \"Body mass (g)\",",
  "    caption = \"Boxes: IQR; Line: median; Whiskers: 1.5×IQR\"",
  "  ) +",
  "  theme(legend.position = \"none\")",
  "```",
  "",
  "### 3) Faceted bars (geom_col + facet_wrap)",
  "```{r}",
  "peng_summary <-",
  "  peng_long |>",
  "  dplyr::group_by(species, island, bill_metric) |>",
  "  dplyr::summarise(mean_mm = mean(mm), .groups = \"drop\")",
  "",
  "ggplot(peng_summary, aes(island, mean_mm, fill = bill_metric)) +",
  "  geom_col(position = \"dodge\") +",
  "  facet_wrap(~ species) +",
  "  labs(",
  "    title = \"Mean bill dimensions by species and island\",",
  "    x = \"Island\", y = \"Mean (mm)\",",
  "    fill = \"Measure\",",
  "    caption = \"Faceted by species\"",
  "  )",
  "```",
  "",
  "## Results summary (4–6 sentences)",
  "",
  "Overall, **Gentoo** penguins exhibit the highest median body mass, while **Adélie** are generally lighter.  ",
  "Bill length and depth show species-specific clusters, with clear separation particularly for Gentoo vs. Adélie.  ",
  "Mean bill dimensions vary across islands, with Biscoe often showing larger averages for Gentoo.  ",
  "These patterns are consistent with ecological and morphological differences documented in the literature.",
  "",
  "::: {.callout-tip}",
  "**Reproducibility note.** All code is runnable end-to-end with dependencies listed in the repo.",
  ":::",
  "",
  "## Functions used (for TA checklist)",
  "",
  "- **dplyr/tidyr:** `drop_na()`, `filter()`, `mutate()`, `select()`, `arrange()`, `pivot_longer()`, `group_by()`, `summarise()`  ",
  "- **ggplot2 geoms/facets:** `geom_point()`, `geom_smooth()`, `geom_boxplot()`, `geom_col()`, `facet_wrap()`"
), "example-analysis.qmd")

writeLines(c(
  "@Manual{quarto,",
  "  title  = {Quarto},",
  "  author = {{Quarto Development Team}},",
  "  year   = {2024},",
  "  url    = {https://quarto.org}",
  "}",
  "@Article{horst2020palmerpenguins,",
  "  title={palmerpenguins: Palmer Archipelago (Antarctica) penguin data},",
  "  author={Horst, Allison M and Hill, Alison P and Gorman, Kristen B},",
  "  journal={Journal of Open Source Software},",
  "  year={2020},",
  "  url={https://allisonhorst.github.io/palmerpenguins/}",
  "}",
  "@Book{ggplot2,",
  "  title={ggplot2: Elegant Graphics for Data Analysis},",
  "  author={Wickham, Hadley},",
  "  year={2016},",
  "  publisher={Springer}",
  "}",
  "@Manual{dplyr,",
  "  title  = {dplyr: A Grammar of Data Manipulation},",
  "  author = {Wickham, Hadley and others},",
  "  year   = {2024},",
  "  url    = {https://dplyr.tidyverse.org}",
  "}",
  "@Manual{tidyr,",
  "  title  = {tidyr: Tidy Messy Data},",
  "  author = {Wickham, Hadley and others},",
  "  year   = {2024},",
  "  url    = {https://tidyr.tidyverse.org}",
  "}"
), "references.bib")

writeLines(c(
  "# biostat777-intro-firstname-lastname",
  "",
  "Public site for Project 1 (biostat777).  ",
  paste0("Author: ", your_name, "."), "",
  "- Deployed website: <ADD-URL-HERE>",
  paste0("- Public repo: <https://github.com/", your_github, "/biostat777-intro-firstname-lastname>"),
  "",
  "Built with Quarto. See `example-analysis.qmd` for the analysis page."
), "README.md")

writeLines(c(
  "---",
  "title: \"Project 1 — Links for Grading\"",
  "format: html",
  "---",
  "",
  "## URLs",
  "",
  paste0("- **Public GitHub repo for website:** https://github.com/", your_github, "/biostat777-intro-firstname-lastname"),
  "- **Deployed website:** <PASTE-URL-HERE>"
), "project1-links.qmd")

# Install packages if missing (safe to re-run)
for (pkg in c("tidyverse","palmerpenguins","janitor")) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
}

message("Scaffold complete. Next: Build → Render Website (or run system('quarto render')).")
